# Base Jekyll configuration

# Note: Grunt handles some Jekyll configuration. If you set something here and
# it doesn't work, check if it is set in the Gruntfile. There is also a
# _config.build.yml to set custom overrides for `grunt build`.

name: portfolio
description: Alex Sanders’ portfolio

author:
  name: Alex Sanders
  email: a@snd.rs
  github: sndrs
  twitter: asanders

# Exclude directories and/or files from the conversion.
# Grunt moves image files and asset directories.
exclude: ['_scss', '_src', 'bower_components', 'image', 'css', 'js', 'fonts', '*.png', '**/*.png', '*.jpg', '**/*.jpg', '*.jpeg', '**/*.jpeg', '*.gif', '**/*.gif', '*.webp', '**/*.webp', '*.svg', '**/*.svg', '*.ico']

# Force inclusion of directories and/or files in the conversion.
# .htaccess is a good example since dotfiles are excluded by default.
include: ['.htaccess']

# Default post path style
# date  /:categories/:year/:month/:day/:title.html
# pretty  /:categories/:year/:month/:day/:title/
# none  /:categories/:title.html
permalink: none

# Publish posts with future date.
# _config.build.yml sets this to false on `grunt build`
future: true

# Compile posts in the _drafts directory.
# _config.build.yml sets this to false on `grunt build`
show_drafts: true

# Markdown library
markdown: maruku
# Markdown library options
# maruku:
  # use_tex:    false
  # use_divs:   false
  # png_engine: blahtex
  # png_dir:    images/latex
  # png_url:    /images/latex

# Use Pygments to highlight code blocks
pygments: false
